const mockEvents = {
  city: {
    id: 1007700,
    city: "München",
    lat: 48.14,
    lon: 11.58,
    state: "",
    country: "de",
    zip: "meetup3",
    member_count: 1257,
  },
  events: [
    {
      created: 1596533710000,
      duration: 3600000,
      id: "272353231",
      name: "Zoll und Außenhandel mit SAP S/4HANA & GTS",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1600243200000,
      local_date: "2020-09-16",
      local_time: "10:00",
      updated: 1596533710000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 1,
      venue: {
        id: 26493437,
        name: "DATACADEMY MUC online",
        lat: 48.13512420654297,
        lon: 11.58198070526123,
        repinned: false,
        address_1: "RSVP -> siehe Eventbeschreibung links",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      is_online_event: false,
      group: {
        created: 1552681092000,
        name: "Munich DATACADEMY",
        id: 31398167,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Munich-Datacademy",
        who: "DATACADEMISTs",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Munich-Datacademy/events/272353231/",
      description:
        "Mit S/4HANA hat SAP einen Paradigmenwechsel im Vergleich zur Vorgängerversion vollzogen. Die Leistungssteigerung und Vereinfachung der Prozesse wurde vor allem durch Konsolidierung erreicht. Leider werden gerade aus diesem Grund viele Außenhandelsfunktionen in S/4HANA nicht mehr unterstützt. Umsteiger sollten sich frühzeitig informieren, welche exportrelevanten Prozesse zukünftig wie abgebildet werden können. Sei es mit den in S/4 HANA vorhandenen Funktionen, durch Add-ons oder sogar durch die Anschaffung von SAP Global Trade System. In dem Live-Webinar adressieren die Experten von Syntax u.a. folgende Fragestellungen: - Welche Zoll- und außenhandelsrelevanten Prozesse können im SAP-Standard wie abgebildet werden? - Welche Kosten entstehen für SAP-GTS Lizenzen, Betrieb/ Wartung und Implementierung? - Wie ist die Reaktionszeit auf rechtliche Änderungen und anstehende Abkommen? - Bilden durch SAP-Partner entwickelte Ad-Ons sowie Schnittstellenlösungen eine attraktive Alternative? Wir freuen uns auf Ihre Teilnahme!",
      visibility: "public",
      pro_is_email_shared: false,
      member_pay_fee: false,
    },
    {
      created: 1581639725000,
      duration: 10800000,
      id: "268694958",
      name: "Unternehmertreffen & Start up-Event in München",
      rsvp_limit: 30,
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1601827200000,
      local_date: "2020-10-04",
      local_time: "18:00",
      updated: 1581946161000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 26865368,
        name: "The Flushing Meadows Bar, Frauenhoferstraße 32, 80469 München",
        lat: 48.128822326660156,
        lon: 11.574684143066406,
        repinned: false,
        address_1: "Frauenhoferstraße 32, 80469 München",
        city: "München",
        country: "DE",
        localized_country_name: "Germany",
      },
      is_online_event: false,
      group: {
        created: 1581635431000,
        name: "Unternehmertreffen and Start up-Event München",
        id: 33341612,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Unternehmertreffen-Start-up-Event-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Unternehmertreffen-Start-up-Event-Munchen/events/268694958/",
      description:
        "DAS UNTERNEHMERTREFFEN „MÜNCHEN“ STARTUP EVENT INVESTOREN / BUSINESS-ANGEL**mehr Details in der Beschreibung. Das Unternehmertreffen Munich-Milan ist das Forum für Geschäftsfreunde in ganz Deutschland. Wir hören gemeinsam spannende Vorträge, veranstalten Aktionen, haben Zeit für informelle Gespräche und bahnen Geschäfte an. Wir sind überparteilich und unabhängig. Und vor allem: Wir haben viel Spaß am Netzwerken! Zahlreiche UNTERNEHMER und STARTUP UNTERNEHMEN aus dem Raum München nehmen teil und freuen sich über Jeden, der unser Netzwerk weiter verstärkt. AUCH STUDENTEN MIT GUTEN IDEEN SIND HERZLICH WILLKOMMEN. Informationen und Tickets finden sich unter: https://www.munich-milan.de/cms/de/unternehmertreffen-muenchen-3.",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1585297132000,
      duration: 7200000,
      id: "269686692",
      name: "Pitch Club Developer Edition #63",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1602698400000,
      local_date: "2020-10-14",
      local_time: "20:00",
      updated: 1585297132000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 2,
      venue: {
        id: 25959917,
        name: "Bar Ludwig II",
        lat: 48.12186813354492,
        lon: 11.58230972290039,
        repinned: false,
        address_1: "Hochstraße 77",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      is_online_event: false,
      group: {
        created: 1539021073000,
        name: "Pitch Club Developer Edition München",
        id: 30141555,
        join_mode: "approval",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Pitch-Club-Developer-Edition-Munchen",
        who: "Mitglieder",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Pitch-Club-Developer-Edition-Munchen/events/269686692/",
      description:
        "Pitch Club is looking for Software Developers and IT-Professionals for its upcoming event Pitch Club Developer Edition #63 on October 14th, 2020 starting at 5 p.m. at Bar Ludwig II (Hochstraße 77, 81541 Munich) in Munich. So this is like a job interview - but reversed! Companies and startups pitch themselves, the HR concepts, jobs and projects they offer to the audience, i.e. the Software Developers and IT-Professionals, who ask tough and hair-raising questions in addition. After the pitches you can get more information in 1-on-1 talks with the companies. All participants are invited to snacks, drinks and maybe you get to know your future employer. After the official part ends at 8 p.m., the event shifts over to the Afterwork Party, accessible for everyone. The participation for the official part as well as catering (including snacks, soft drinks, beverages &amp; long drinks) are for free! If you want to participate at the invite-only event, starting at 5 p.m., please apply via https://pcde.io/en/. Please note: Most pitches will be held in German. Nonetheless, English-speaking developers are welcomed, too! If you are interested in taking part at the Afterwork Party, starting at 8 p.m., please register via https://pcde.io/en/pcde-afterwork/",
      visibility: "public",
      member_pay_fee: false,
    },
    {
      created: 1594142093000,
      duration: 7200000,
      id: "271775637",
      name: "Beer, Brotzeit and IoT @ Concept Reply",
      date_in_series_pattern: false,
      status: "upcoming",
      time: 1603386000000,
      local_date: "2020-10-22",
      local_time: "19:00",
      updated: 1594142093000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 30,
      venue: {
        id: 26066109,
        name: "Luise-Ullrich-Straße 14",
        lat: 48.14474868774414,
        lon: 11.538175582885742,
        repinned: true,
        address_1: "Luise-Ullrich-Straße 14",
        city: "München",
        country: "de",
        localized_country_name: "Germany",
      },
      is_online_event: false,
      group: {
        created: 1508251656000,
        name: "München IoT Meetup",
        id: 26294946,
        join_mode: "open",
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: "Muenchen-IoT-Meetup",
        who: "Members",
        localized_location: "München, Germany",
        state: "",
        country: "de",
        region: "en_US",
        timezone: "Europe/Berlin",
      },
      link: "https://www.meetup.com/Muenchen-IoT-Meetup/events/271775637/",
      description:
        "We will also broadcast the event live for people who would rather stay at home. We will post the link closer to the event. How to find the new venue: Enter the Nove Building from Luise-Ullrich-Straße 14 (you should see a statue and a restaurant outside). On entering you will see the main reception in front of you with a security guard, two lifts to the left and a model of the building to the right. Walk toward the reception, take the first left and walk toward the other two lifts in front of you. The first door on the left with the Reply logo leads to the Meetup on the *ground floor*. Agenda: 18:30: Brotzeit 19:00: Markus Jung (OSRAM) - The OSRAM portfolio of IoT connected products 19:30: Christopher Ziegler (Actyx.io) - The modern way of automating and digitizing factories 20:00: Networking. Food and drink served throughout. All presentations in English.",
      how_to_find_us:
        "Public transport: Donnersbergerstraße | 250m (Tram 16, 17) Donnersbergerbrücke | 450m (Suburban train towards Pasing, Bus 53 & 63) Address: Concept Reply (part of REPLY AG) Nove building Luise-Ullrich-Straße 14 80636 München*Reply Büro beim EG*",
      visibility: "public",
      member_pay_fee: false,
    },
  ],
};
export { mockEvents };
